version: '3'
services:
  gitbucket:
    build: gitbucket-build
    container_name: gitbucket
    volumes:
      - ./gitbucket_data:/gitbucket
    ports:
      - "8090:8080"

  postgres:
    image: postgres:10.4
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

